# Generated by Django 5.1 on 2025-02-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weekdays',
            new_name='weekday',
        ),
    ]
