# Generated by Django 5.1 on 2025-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_extralesson_is_online_extralesson_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_teacher_date_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала повторений'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'start_date', 'start_time'), name='unique_teacher_start_time'),
        ),
    ]
