# Generated by Django 5.1 on 2025-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_weekdays_schedule_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extralesson',
            name='closed_group',
        ),
        migrations.AlterField(
            model_name='extralesson',
            name='is_individual',
            field=models.BooleanField(default=True, verbose_name='Индивидуальный урок'),
        ),
    ]
