# Generated by Django 5.1 on 2025-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_extralesson_closed_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extralesson',
            name='is_individual',
            field=models.CharField(max_length=200, verbose_name='Инициалы студента'),
        ),
    ]
