# Generated by Django 5.1 on 2025-01-28 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_schedule_unique_teacher_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extralesson',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='Аудитория'),
        ),
    ]
