# Generated by Django 5.1 on 2025-02-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_extralesson_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_individual_online',
            field=models.BooleanField(blank=True, default=False, verbose_name='Индивидуальная ученик онлайн'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_individual',
            field=models.BooleanField(blank=True, default=False, verbose_name='Индивидуальный ученик офлайн'),
        ),
    ]
