# Generated by Django 5.1 on 2025-01-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dayofweek_day_alter_extralesson_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extralesson',
            name='groupe',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='extralesson',
            name='student',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
